name: O My Genshin

on:
  push:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: genshin-sign
        env: 
          COOKIE: ${{secrets.COOKIE}}
        run: |
          docker pull yindan/genshinhelper
          docker run genshinhelper -e COOKIE_HOYOLAB = COOKIE
