name: O My Genshin

on:
  push:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: genshin-sign
        env: 
          COOKIE: ${{secrets.COOKIE}}
        run: |
          pip install genshinhelper
          python3
          import genshinhelper as gh
          cookie = COOKIE
          g = gh.Genshin(cookie)
          roles = g.roles_info
          print(roles)
